name: flutter_skeleton
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_icons:
  android: true
  ios: true
